In [ ]:
!pip install transformers==4.46.3

Collecting transformers==4.46.3
  Downloading transformers-4.46.3-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (3.29.7)
Collecting huggingface-hub<1.0,>=0.23.2 (from transformers==4.46.3)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (2.32.4)
Collecting tokenizers<0.21,>=0.20 (from transformers==4.46.3)
  Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.46.3) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.3) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.46.3) (2026.6.17)
Downloading transformers-4.46.3-py3-none-any.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 121.0 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 31.0 MB/s eta 0:00:00
Downloading tokenizers-0.20.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 123.3 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.23.0
    Uninstalling huggingface_hub-1.23.0:
      Successfully uninstalled huggingface_hub-1.23.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.13.1
    Uninstalling transformers-5.13.1:
      Successfully uninstalled transformers-5.13.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
Successfully installed huggingface-hub-0.36.2 tokenizers-0.20.3 transformers-4.46.3

In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
import pandas as pd
from transformers import pipeline
# pipeline is a readymade workflow
from datasets import load_dataset

In [ ]:

email = """Congratulations! You've Secured Your Spot in the Learnbay Data Science Internship Jan 2026 Program! 🌟
Dear Applicant,

Congratulations!


We are thrilled to inform you that your profile has been shortlisted for the prestigious Learnbay Data Science Internship Program, January 2026.
Welcome to the journey of learning, growth, and exciting opportunities!

Let's celebrate your achievement with some impressive numbers. This year, we received a staggering 20,000 applications, and you stand out as one of the top 10% who made it through our rigorous screening process. Your dedication and skills truly set you apart!

To formalize your acceptance and proceed with the onboarding process, we kindly ask you to complete your profile by filling out the following form: Form Link. If you've already submitted the form, please disregard this message. The deadline to fill the form is January 18, 2026 by 5:00 PM IST.

Important Dates to Remember:
1. Internship Offer Letters and Zoom link to join the internship will be shared via email on January 22, 2026
2. Internship Start Date is January 24, 2026
   - Timing: 6:00 PM to 7:00 PM IST

Feel free to share this exciting news with your friends and family. We look forward to welcoming you to the Learnbay community and embarking on this rewarding journey together.

Congratulations once again, and get ready for an incredible experience!

Best regards,
Learnbay Data Science Internship Team
"""

# SENTIMENT ANALYSIS  - POSITIVE NEGATIVE

In [ ]:
classifier = pipeline(task="text-classification")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [ ]:
classifier(email)

[{'label': 'POSITIVE', 'score': 0.9997065663337708}]

In [ ]:
review = """
I was eagerly waiting for this film and I was not disappointed.
Baahubali is one of the most visually impressive films that have come from India. Everything about this film is good - Story, direction, beautiful cinematography, haunting score and amazing visuals (though they lack some details at some places).
I didn't know who Rajamouli was, basically because I am from North India and I don't follow south Indian cinema. But I am sure he is someone you should know about. SS Rajamouli is amazing. He has made something that we can be proud of. I was sure that the VFX would be good however I had a doubt about the story. Rajamouli proved me wrong with this film. The story and the execution is really good. Story takes elements from Indian mythologies (specially from the life of Lord Krishna) . You can not expect more. He took a big risk and made it big. This is what we need, good quality cinema. Salman fans should learn something from it.
All the actors are good and perform their part really well(except Tamanna. She tries too hard but fails miserably). In fact, Tamanna has been used as a plot device (A MacGuffin as Alfred Hitchcock used to call it). Prabhas is okay in the beginning but transforms into a behemoth during the second half. This guy is a natural. He doesn't act exceptionaly but his presence is enough to give you the feels.
The background score needs special mention because it is amazing. It is different from anything you have ever heard in India. The score that plays during war is haunting. (Clearly inspired from the LotR)
I would be lying if I didn't say that Rajamouli spent a lot of time watching The Lord of The Rings. Yes, some scenes will remind you of 300 and the Lord of The Rings but believe me it is completely different. He doesn't copy anything, he uses it as a source of inspiration. There is only one scene that I remember from LotR which has been used in Baahubali. But denying that he was influenced by Peter Jackson would be a big lie. Its a great thing that he was influenced by such a great film otherwise we wouldn't have Baahubali.
"""

In [ ]:
classifier(review)

[{'label': 'POSITIVE', 'score': 0.9997075200080872}]

In [ ]:
review1 = """
I am extremely  disappointed.
this is one of the most visually worst films that have come from India. Everything about this film is bad - Story, direction, beautiful cinematography, haunting score and amazing visuals (though they lack some details at some places).
I didn't know who director was. I was sure that the VFX could  be better however I had a doubt about the story. R ).
This was waste of money and time
"""

In [ ]:
classifier(review1)

[{'label': 'NEGATIVE', 'score': 0.9992407560348511}]

In [ ]:
review2 = """
 I went out in the evening to the garden.
"""

In [ ]:
classifier(review2)

[{'label': 'POSITIVE', 'score': 0.9780896306037903}]

# text summarisation

In [ ]:
summarizer = pipeline(task="summarization", max_length=62)

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [ ]:
editorial = """
At the midnight hour on a magical Sunday, Harmanpreet Kaur and her incredible women made their tryst with destiny. India was finally crowned world champions in women’s cricket. It was a journey marked by a long history of angst and joy, shaped by the sweat and dreams of pioneers such as Shantha Rangaswamy, Diana Edulji, Mithali Raj, and Jhulan Goswami. In a high-stakes final befitting an ICC World Cup, India prevailed over South Africa by 52 runs at Navi Mumbai’s D.Y. Patil Stadium, which turned into a teeming mass of raucous energy. This moment is as epochal as it was for Kapil Dev and his men in 1983 when they seized the World Cup at Lord’s. That caused a seismic shift in the way cricket was perceived and administered and paved the way for India to become a commercial behemoth. A similar turn of events awaits Harmanpreet and company, and women’s cricket at large. The coach, Amol Muzumdar, too had his moment. A domestic giant, he never got a chance to play for the senior men’s team as his career ran parallel to the likes of Sachin Tendulkar and Rahul Dravid. Harmanpreet’s feisty women ensured that their mentor finally understood what it means to prosper at the highest level.
Having faltered in the 2005 and 2017 World Cup finals, India also had to contend with the pressure of playing at home. When three league matches were lost on the trot against South Africa, Australia, and England, the knives were out on social media. Still, the team persevered and every game produced a new star — Pratika Rawal, for instance. In the final, Shafali Verma and Deepti Sharma turned in an all-round show, while Smriti Mandhana was as solid as ever. Earlier, the turn towards glory happened in the semifinal when Jemimah Rodrigues anchored an astounding chase against defending champions Australia. Her unbeaten 127 is one of the greatest knocks in Indian cricketing history. If India performed the giant killing act towards the climactic phase, so too did South Africa, as England discovered in the semifinal. In skipper Laura Wolvaardt, the Proteas have a splendid batter and her two tons in the semifinal and final were high on class and pugnacity. But the biggest takeaway is this: Indian women have found their place on cricket’s biggest stage.
"""

In [ ]:
summarizer(editorial)

[{'summary_text': " India beat South Africa by 52 runs at Navi Mumbai's D.Y. Patil Stadium . Harmanpreet Kaur and her incredible women made their tryst with destiny . This moment is as epochal as it was for Kapil Dev and his men in 1983 when they seized the"}]

In [ ]:
summarizer(email)

[{'summary_text': ' The deadline to fill the form is January 18, 2026 by 5:00 PM IST . The internship offer letters and Zoom link to join the internship will be shared via email on January 22, 20 26 . Internship start date is January 24, 2024 - Timing: 6:00'}]

In [ ]:
summarizer = pipeline(task="summarization")

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 and revision a4f8f3e (https://huggingface.co/sshleifer/distilbart-cnn-12-6).
Using a pipeline without specifying a model name and revision in production is not recommended.
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [ ]:
summarizer(email)

[{'summary_text': ' The deadline to fill the form is January 18, 2026 by 5:00 PM IST . The internship offer letters and Zoom link to join the internship will be shared via email on January 22, 20 26 . Internship start date is January 24, 2024 - Timing: 6:00pm to 7:00PM IST .'}]

In [ ]:
summarizer(editorial)

[{'summary_text': " India beat South Africa by 52 runs at Navi Mumbai's D.Y. Patil Stadium . Harmanpreet Kaur and her incredible women made their tryst with destiny . This is as epochal as it was for Kapil Dev and his men in 1983 when they seized the World Cup at Lord’s ."}]

#NER - NAMED ENTITIY RECOGNITION

In [ ]:
ner_tagger = pipeline("ner")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [ ]:
sent1 = "Apple is good for health. "
sent2 = "Apple is planning to buy Sumsung"
sent3 = "Apple is good for health. It keeps doctor away"

In [ ]:
ner_tagger(sent1)

[{'entity': 'I-MISC',
  'score': np.float32(0.60477453),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5}]

In [ ]:
ner_tagger(sent2)

[{'entity': 'I-ORG',
  'score': np.float32(0.9991905),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5},
 {'entity': 'I-ORG',
  'score': np.float32(0.9663403),
  'index': 6,
  'word': 'Su',
  'start': 25,
  'end': 27},
 {'entity': 'I-ORG',
  'score': np.float32(0.41728878),
  'index': 7,
  'word': '##ms',
  'start': 27,
  'end': 29},
 {'entity': 'I-ORG',
  'score': np.float32(0.9824118),
  'index': 8,
  'word': '##ung',
  'start': 29,
  'end': 32}]

In [ ]:
ner_tagger(sent3)

[{'entity': 'I-MISC',
  'score': np.float32(0.532613),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5}]

In [ ]:
ner_tagger(review)

[{'entity': 'I-MISC',
  'score': np.float32(0.9899888),
  'index': 14,
  'word': 'Ba',
  'start': 65,
  'end': 67},
 {'entity': 'I-MISC',
  'score': np.float32(0.95721495),
  'index': 15,
  'word': '##ahu',
  'start': 67,
  'end': 70},
 {'entity': 'I-MISC',
  'score': np.float32(0.97629493),
  'index': 16,
  'word': '##bal',
  'start': 70,
  'end': 73},
 {'entity': 'I-MISC',
  'score': np.float32(0.9837338),
  'index': 17,
  'word': '##i',
  'start': 73,
  'end': 74},
 {'entity': 'I-LOC',
  'score': np.float32(0.9986687),
  'index': 30,
  'word': 'India',
  'start': 140,
  'end': 145},
 {'entity': 'I-PER',
  'score': np.float32(0.99917334),
  'index': 70,
  'word': 'Raja',
  'start': 329,
  'end': 333},
 {'entity': 'I-PER',
  'score': np.float32(0.9954997),
  'index': 71,
  'word': '##mo',
  'start': 333,
  'end': 335},
 {'entity': 'I-PER',
  'score': np.float32(0.98545814),
  'index': 72,
  'word': '##uli',
  'start': 335,
  'end': 338},
 {'entity': 'I-LOC',
  'score': np.float32(0.9885266),
  'index': 80,
  'word': 'North',
  'start': 372,
  'end': 377},
 {'entity': 'I-LOC',
  'score': np.float32(0.99087524),
  'index': 81,
  'word': 'India',
  'start': 378,
  'end': 383},
 {'entity': 'I-MISC',
  'score': np.float32(0.99844164),
  'index': 89,
  'word': 'Indian',
  'start': 409,
  'end': 415},
 {'entity': 'I-PER',
  'score': np.float32(0.9979448),
  'index': 104,
  'word': 'SS',
  'start': 475,
  'end': 477},
 {'entity': 'I-PER',
  'score': np.float32(0.9993849),
  'index': 105,
  'word': 'Raja',
  'start': 478,
  'end': 482},
 {'entity': 'I-PER',
  'score': np.float32(0.9958746),
  'index': 106,
  'word': '##mo',
  'start': 482,
  'end': 484},
 {'entity': 'I-PER',
  'score': np.float32(0.9910897),
  'index': 107,
  'word': '##uli',
  'start': 484,
  'end': 487},
 {'entity': 'I-PER',
  'score': np.float32(0.9991345),
  'index': 142,
  'word': 'Raja',
  'start': 624,
  'end': 628},
 {'entity': 'I-PER',
  'score': np.float32(0.99122006),
  'index': 143,
  'word': '##mo',
  'start': 628,
  'end': 630},
 {'entity': 'I-PER',
  'score': np.float32(0.96408236),
  'index': 144,
  'word': '##uli',
  'start': 630,
  'end': 633},
 {'entity': 'I-MISC',
  'score': np.float32(0.99894637),
  'index': 165,
  'word': 'Indian',
  'start': 736,
  'end': 742},
 {'entity': 'I-PER',
  'score': np.float32(0.6293025),
  'index': 174,
  'word': 'Lord',
  'start': 783,
  'end': 787},
 {'entity': 'I-PER',
  'score': np.float32(0.9986033),
  'index': 175,
  'word': 'Krishna',
  'start': 788,
  'end': 795},
 {'entity': 'I-PER',
  'score': np.float32(0.7958639),
  'index': 204,
  'word': 'Sal',
  'start': 903,
  'end': 906},
 {'entity': 'I-PER',
  'score': np.float32(0.8536884),
  'index': 205,
  'word': '##man',
  'start': 906,
  'end': 909},
 {'entity': 'I-PER',
  'score': np.float32(0.98254675),
  'index': 226,
  'word': 'Tam',
  'start': 1013,
  'end': 1016},
 {'entity': 'I-PER',
  'score': np.float32(0.95081043),
  'index': 227,
  'word': '##anna',
  'start': 1016,
  'end': 1020},
 {'entity': 'I-MISC',
  'score': np.float32(0.7348664),
  'index': 243,
  'word': 'Tam',
  'start': 1072,
  'end': 1075},
 {'entity': 'I-MISC',
  'score': np.float32(0.92404824),
  'index': 244,
  'word': '##anna',
  'start': 1075,
  'end': 1079},
 {'entity': 'I-MISC',
  'score': np.float32(0.96078765),
  'index': 254,
  'word': 'Mac',
  'start': 1114,
  'end': 1117},
 {'entity': 'I-MISC',
  'score': np.float32(0.97415763),
  'index': 255,
  'word': '##G',
  'start': 1117,
  'end': 1118},
 {'entity': 'I-MISC',
  'score': np.float32(0.6144396),
  'index': 256,
  'word': '##uff',
  'start': 1118,
  'end': 1121},
 {'entity': 'I-MISC',
  'score': np.float32(0.96779287),
  'index': 257,
  'word': '##in',
  'start': 1121,
  'end': 1123},
 {'entity': 'I-PER',
  'score': np.float32(0.99431074),
  'index': 259,
  'word': 'Alfred',
  'start': 1127,
  'end': 1133},
 {'entity': 'I-PER',
  'score': np.float32(0.9933553),
  'index': 260,
  'word': 'Hitchcock',
  'start': 1134,
  'end': 1143},
 {'entity': 'I-PER',
  'score': np.float32(0.9992592),
  'index': 267,
  'word': 'P',
  'start': 1162,
  'end': 1163},
 {'entity': 'I-PER',
  'score': np.float32(0.95865226),
  'index': 268,
  'word': '##rab',
  'start': 1163,
  'end': 1166},
 {'entity': 'I-PER',
  'score': np.float32(0.9883571),
  'index': 269,
  'word': '##has',
  'start': 1166,
  'end': 1169},
 {'entity': 'I-LOC',
  'score': np.float32(0.9989993),
  'index': 332,
  'word': 'India',
  'start': 1470,
  'end': 1475},
 {'entity': 'I-MISC',
  'score': np.float32(0.43568918),
  'index': 349,
  'word': '##R',
  'start': 1552,
  'end': 1553},
 {'entity': 'I-PER',
  'score': np.float32(0.9989722),
  'index': 362,
  'word': 'Raja',
  'start': 1593,
  'end': 1597},
 {'entity': 'I-PER',
  'score': np.float32(0.99397993),
  'index': 363,
  'word': '##mo',
  'start': 1597,
  'end': 1599},
 {'entity': 'I-PER',
  'score': np.float32(0.9795634),
  'index': 364,
  'word': '##uli',
  'start': 1599,
  'end': 1602},
 {'entity': 'I-MISC',
  'score': np.float32(0.91819644),
  'index': 371,
  'word': 'The',
  'start': 1632,
  'end': 1635},
 {'entity': 'I-MISC',
  'score': np.float32(0.99715173),
  'index': 372,
  'word': 'Lord',
  'start': 1636,
  'end': 1640},
 {'entity': 'I-MISC',
  'score': np.float32(0.9908922),
  'index': 373,
  'word': 'of',
  'start': 1641,
  'end': 1643},
 {'entity': 'I-MISC',
  'score': np.float32(0.99559504),
  'index': 374,
  'word': 'The',
  'start': 1644,
  'end': 1647},
 {'entity': 'I-MISC',
  'score': np.float32(0.9873749),
  'index': 375,
  'word': 'Rings',
  'start': 1648,
  'end': 1653},
 {'entity': 'I-PER',
  'score': np.float32(0.7901745),
  'index': 388,
  'word': 'Lord',
  'start': 1703,
  'end': 1707},
 {'entity': 'I-PER',
  'score': np.float32(0.9967584),
  'index': 432,
  'word': 'Ba',
  'start': 1902,
  'end': 1904},
 {'entity': 'I-PER',
  'score': np.float32(0.99144745),
  'index': 433,
  'word': '##ahu',
  'start': 1904,
  'end': 1907},
 {'entity': 'I-PER',
  'score': np.float32(0.99926585),
  'index': 444,
  'word': 'Peter',
  'start': 1951,
  'end': 1956},
 {'entity': 'I-PER',
  'score': np.float32(0.999385),
  'index': 445,
  'word': 'Jackson',
  'start': 1957,
  'end': 1964},
 {'entity': 'I-PER',
  'score': np.float32(0.99686605),
  'index': 471,
  'word': 'Ba',
  'start': 2074,
  'end': 2076},
 {'entity': 'I-PER',
  'score': np.float32(0.993497),
  'index': 472,
  'word': '##ahu',
  'start': 2076,
  'end': 2079}]

In [ ]:
ner_tagger(email)

[{'entity': 'I-MISC',
  'score': np.float32(0.8804024),
  'index': 14,
  'word': 'Lea',
  'start': 49,
  'end': 52},
 {'entity': 'I-ORG',
  'score': np.float32(0.6564434),
  'index': 15,
  'word': '##rn',
  'start': 52,
  'end': 54},
 {'entity': 'I-ORG',
  'score': np.float32(0.50340855),
  'index': 16,
  'word': '##bay',
  'start': 54,
  'end': 57},
 {'entity': 'I-MISC',
  'score': np.float32(0.54433167),
  'index': 17,
  'word': 'Data',
  'start': 58,
  'end': 62},
 {'entity': 'I-ORG',
  'score': np.float32(0.74238545),
  'index': 18,
  'word': 'Science',
  'start': 63,
  'end': 70},
 {'entity': 'I-MISC',
  'score': np.float32(0.8582574),
  'index': 19,
  'word': 'Inter',
  'start': 71,
  'end': 76},
 {'entity': 'I-MISC',
  'score': np.float32(0.92459345),
  'index': 21,
  'word': '##hip',
  'start': 78,
  'end': 81},
 {'entity': 'I-MISC',
  'score': np.float32(0.99656785),
  'index': 52,
  'word': 'Lea',
  'start': 227,
  'end': 230},
 {'entity': 'I-MISC',
  'score': np.float32(0.54141665),
  'index': 53,
  'word': '##rn',
  'start': 230,
  'end': 232},
 {'entity': 'I-MISC',
  'score': np.float32(0.9018482),
  'index': 54,
  'word': '##bay',
  'start': 232,
  'end': 235},
 {'entity': 'I-MISC',
  'score': np.float32(0.9469919),
  'index': 55,
  'word': 'Data',
  'start': 236,
  'end': 240},
 {'entity': 'I-MISC',
  'score': np.float32(0.77005017),
  'index': 56,
  'word': 'Science',
  'start': 241,
  'end': 248},
 {'entity': 'I-MISC',
  'score': np.float32(0.9632907),
  'index': 57,
  'word': 'Inter',
  'start': 249,
  'end': 254},
 {'entity': 'I-MISC',
  'score': np.float32(0.62775576),
  'index': 58,
  'word': '##ns',
  'start': 254,
  'end': 256},
 {'entity': 'I-MISC',
  'score': np.float32(0.94304514),
  'index': 59,
  'word': '##hip',
  'start': 256,
  'end': 259},
 {'entity': 'I-MISC',
  'score': np.float32(0.98655033),
  'index': 60,
  'word': 'Program',
  'start': 260,
  'end': 267},
 {'entity': 'I-ORG',
  'score': np.float32(0.8220316),
  'index': 282,
  'word': 'Lea',
  'start': 1241,
  'end': 1244},
 {'entity': 'I-ORG',
  'score': np.float32(0.74560636),
  'index': 283,
  'word': '##rn',
  'start': 1244,
  'end': 1246},
 {'entity': 'I-ORG',
  'score': np.float32(0.93973887),
  'index': 284,
  'word': '##bay',
  'start': 1246,
  'end': 1249},
 {'entity': 'I-ORG',
  'score': np.float32(0.9977233),
  'index': 313,
  'word': 'Lea',
  'start': 1398,
  'end': 1401},
 {'entity': 'I-ORG',
  'score': np.float32(0.93745303),
  'index': 314,
  'word': '##rn',
  'start': 1401,
  'end': 1403},
 {'entity': 'I-ORG',
  'score': np.float32(0.9880657),
  'index': 315,
  'word': '##bay',
  'start': 1403,
  'end': 1406},
 {'entity': 'I-ORG',
  'score': np.float32(0.9934248),
  'index': 316,
  'word': 'Data',
  'start': 1407,
  'end': 1411},
 {'entity': 'I-ORG',
  'score': np.float32(0.9802579),
  'index': 317,
  'word': 'Science',
  'start': 1412,
  'end': 1419},
 {'entity': 'I-ORG',
  'score': np.float32(0.8775329),
  'index': 318,
  'word': 'Inter',
  'start': 1420,
  'end': 1425},
 {'entity': 'I-ORG',
  'score': np.float32(0.5783125),
  'index': 319,
  'word': '##ns',
  'start': 1425,
  'end': 1427},
 {'entity': 'I-ORG',
  'score': np.float32(0.6360789),
  'index': 320,
  'word': '##hip',
  'start': 1427,
  'end': 1430},
 {'entity': 'I-ORG',
  'score': np.float32(0.907847),
  'index': 321,
  'word': 'Team',
  'start': 1431,
  'end': 1435}]

# QNA - question-answer

In [ ]:
reader = pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [ ]:
email

"Congratulations! You've Secured Your Spot in the Learnbay Data Science Internship Jan 2026 Program! 🌟\nDear Applicant,\n\nCongratulations!\n\n\nWe are thrilled to inform you that your profile has been shortlisted for the prestigious Learnbay Data Science Internship Program, January 2026.\nWelcome to the journey of learning, growth, and exciting opportunities!\n\nLet's celebrate your achievement with some impressive numbers. This year, we received a staggering 20,000 applications, and you stand out as one of the top 10% who made it through our rigorous screening process. Your dedication and skills truly set you apart!\n\nTo formalize your acceptance and proceed with the onboarding process, we kindly ask you to complete your profile by filling out the following form: Form Link. If you've already submitted the form, please disregard this message. The deadline to fill the form is January 18, 2026 by 5:00 PM IST.\n\nImportant Dates to Remember:\n1. Internship Offer Letters and Zoom link to join the internship will be shared via email on January 22, 2026\n2. Internship Start Date is January 24, 2026\n   - Timing: 6:00 PM to 7:00 PM IST\n\nFeel free to share this exciting news with your friends and family. We look forward to welcoming you to the Learnbay community and embarking on this rewarding journey together.\n\nCongratulations once again, and get ready for an incredible experience!\n\nBest regards,\nLearnbay Data Science Internship Team\n"

In [ ]:
question = "When are we going to receive an offer letter?"
reader(question=question, context=email)

{'score': 0.5336119532585144,
 'start': 1034,
 'end': 1052,
 'answer': 'January 22, 2026\n2'}

In [ ]:
reliance = """
Reliance Industries Limited is an Indian multinational conglomerate headquartered in Mumbai. Its businesses include energy, petrochemicals, natural gas, retail, entertainment, telecommunications, mass media, and textiles. Reliance is the largest public company in India by market capitalisation[6][7] and revenue,[8] and the 86th largest company worldwide.[9] It is India's largest private tax payer[10] and largest exporter, accounting for 7% of India's total merchandise exports.[11]

The company has attracted controversy for reports of political corruption, cronyism, fraud, financial manipulation, and exploitation of its customers, Indian citizens, and natural resources.[12][13][14][15][16] Its chairman, Mukesh Ambani, has been described as a plutocrat.[17]

History
1958–1985

Stamp released in 2002 to honor company founder Dhirubhai Ambani
Reliance Commercial Corporation was set up in 1958 by Dhirubhai Ambani as a small venture firm trading commodities, especially spices and polyester yarn.[1] In 1965, the partnership ended and Dhirubhai continued the polyester business of the firm.[18] In 1966, Reliance Textiles Industries Pvt. Ltd. was incorporated in Maharashtra. It established a synthetic fabrics mill in the same year at Naroda in Gujarat.[19] On 8 May 1973, it became Reliance Textiles Industries Limited. In 1975, the company expanded its business into textiles, with "Vimal" becoming its major brand in later years. The company held its initial public offering (IPO) in 1977.[20] The issue was over-subscribed by seven times.[21] In 1979, a textiles company Sidhpur Mills was amalgamated with the company.[22] In 1980, the company expanded its polyester yarn business by setting up a Polyester Filament Yarn Plant in Patalganga, Raigad, Maharashtra with financial and technical collaboration with E. I. du Pont de Nemours & Co., U.S.[19]

1981–2000
In 1985, the name of the company was changed from Reliance Textiles Industries Ltd. to Reliance Industries Ltd.[19] During 1985 to 1992, the company expanded its installed capacity for producing polyester yarn by over 145,000 tonnes per annum.[19]

The Hazira petrochemical plant was commissioned in 1991–92.[23]

In 1993, Reliance turned to the overseas capital markets for funds through a global depository issue of Reliance Petroleum. In 1996, it became the first private sector company in India to be rated by international credit rating agencies. S&P rated Reliance "BB+, stable outlook, constrained by the sovereign ceiling". Moody's rated "Baa3, Investment grade, constrained by the sovereign ceiling".[24]

In 1995/96, the company entered the telecommunications industry through a joint venture with NYNEX, USA, and promoted Reliance Telecom Private Limited in India.[23]

In 1998, Reliance took over Indian Petrochemicals Corporation Limited during privatization of public sector enterprises.

In 1998/99, RIL introduced packaged LPG in 15 kg cylinders under the brand name Reliance Gas.[23]

The years 1998–2000 saw the construction of the integrated petrochemical complex at Jamnagar in Gujarat,[23] the largest refinery in the world.

2001 onwards
In 2001, Reliance Industries Ltd. and Reliance Petroleum Ltd. became India's two largest companies in terms of all major financial parameters.[25] In 2001–02, Reliance Petroleum was merged with Reliance Industries.[20]

In 2002, Reliance announced India's biggest gas discovery (at the Krishna Godavari basin) in nearly three decades and one of the largest gas discoveries in the world during 2002. The in-place volume of natural gas was more than 7 trillion cubic feet, equivalent to about 120 crore (1.2 billion) barrels of crude oil. This was the first-ever discovery by an Indian private sector company.[20][non-primary source needed][26]

In 2002–03, RIL purchased a majority stake in Indian Petrochemicals Corporation Ltd. (IPCL), India's second largest petrochemicals company, from the government of India,[27] RIL took over IPCL's Vadodara Plants and renamed it as Vadodara Manufacturing Division (VMD).[28][29] IPCL's Nagothane and Dahej manufacturing complexes came under RIL when IPCL was merged with RIL in 2008.[30][31]

In 2005 and 2006, the company reorganised its business by demerging its investments in power generation and distribution, financial services and telecommunication services into four separate entities.[32][non-primary source needed]

In 2006, Reliance entered the organised retail market in India[33] with the launch of its retail store format under the brand name of 'Reliance Fresh'.[34][35] By the end of 2008, Reliance Retail had close to 600 stores across 57 cities in India.[20][non-primary source needed] [36]

In November 2009, Reliance Industries issued 1:1 bonus shares to its shareholders.[37][38]

In 2010, Reliance entered the broadband services market with acquisition of Infotel Broadband Services Limited, which was the only successful bidder for pan-India fourth-generation (4G) spectrum auction held by the government of India.[39][40] In the same year, Reliance and BP announced a partnership in the oil and gas business. BP took a 30 per cent stake in 23 oil and gas production sharing contracts that Reliance operates in India, including the KG-D6 block for $7.2 billion.[41] Reliance also formed a 50:50 joint venture with BP for sourcing and marketing of gas in India.[42]

In 2017, RIL set up a joint venture with Russian Company Sibur for setting up a Butyl rubber plant in Jamnagar, Gujarat, to be operational by 2018.[43]

In 2018, the Commercial Court (England and Wales), hearing a legal case involving Reliance Industries and the Union of India, ruled for the first time that the foreign act of state doctrine applied when issues were being addressed through arbitration, as well as when they are addressed through litigation.[44]

In August 2019, Reliance added Fynd[45] primarily for its consumer businesses and mobile phone services in the e-commerce space.[46][47]

In December 2022, Reliance Industries Market cap stood at ₹17.59 lakh crore (US$223.78 billion).[48]

In the field of generative pre-trained transformer (GPT) technology, Reliance Industries Ltd. and The BharatGPT Group announced in February 2024 that they would launch a large language model (LLM), Hanuman's AI system, in March 2024. The model will work in 11 local languages in four major areas: health, governance, financial services and education.[49]

In February 2024, Reliance and The Walt Disney Company announced a deal to merge their streaming and television assets.[50][51] The deal was closed in November 2024, with the Disney Star joint venture having a reported value of $8.5 billion.[52]

In October 2024, Reliance entered into an agreement with Nvidia to procure Blackwell chips for its planned data centre in Jamnagar.[53]

On 3 June 2025, it was reported that Reliance Industries-owned Jai Ammunition Limited was part of an Indian Army project to supply indigenously designed, developed and produced artillery shells and reduce foreign dependence. As of date, four ammunition variants – including high explosive, smoke and dual-purpose improved conventional munition (DPICM) rounds – have been tested for the past two years. The final development-cum-user trials are planned in November 2025, following which mass order could be placed. The shells have been developed under the Development Cum Production Partner (DCPP) programme by the Defence Research and Development Organisation (DRDO) with two industry partners – Jai Ammunition and Yantra India.[54]

Shareholding
The number of shares of RIL are approx. 644.51 crore (6.44 billion).[55] The promoter group, the Ambani family, holds 50.39% of the total shares whereas the remaining 49.61% shares are held by public shareholders, including FII and corporate bodies.[55] Life Insurance Corporation of India, public sector company, is the largest non-promoter investor in the company, with 6.49% shareholding.[56]

In January 2012, the company announced a buyback program to buy a maximum of 12 crore (120 million) shares for ₹10,400 crore (US$1.95 billion). By the end of January 2013, the company had bought back 4.62 crore (46.2 million) shares for ₹3,366 crore (US$574.42 million).[57]

Listing
The company's equity shares are listed on the National Stock Exchange of India Limited (NSE) and the BSE Limited. The Global Depository Receipts (GDRs) issued by the company are listed on London Stock Exchange.[58][59] It has issued approx. 5.6 crore (56 million) GDRs wherein each GDR is equivalent to two equity shares of the company. Approximately 3.46% of its total shares are listed on Luxembourg Stock Exchange.[55][non-primary source needed]

Its debt securities are listed at the Wholesale Debt Market (WDM) Segment of the National Stock Exchange of India Limited (NSE).[60][non-primary source needed]

It has received domestic credit ratings of AAA from CRISIL (S&P subsidiary) and Fitch. Moody's and S&P have provided investment grade ratings for international debt of the company, as Baa2 positive outlook (local currency issuer rating) and BBB+ outlook respectively.[61][non-primary source needed][62][63]

On 28 December 2017, RIL announced that it will be acquiring the wireless assets of Anil Ambani-led Reliance Communications for about ₹23,000 crores.[64]

Operations
The company's petrochemical, refining, and oil and gas-related operations form the core of its business; other divisions of the company include cloth, retail, telecommunications, and special economic zone (SEZ) development.

Revenue by segment (2024)[65]
Segment	Share of revenue
Oil to Chemicals	53.12%
Retail	26.68%
Digital Services	11.05%
Others	6.77%
Oil and Gas	2.38%
In July 2012, RIL informed that it was going to invest US$1 billion over the next few years in its new aerospace division which will design, develop and manufacture equipment and components, including aircraft, engine, radars, avionics and accessories for military and civilian aircraft, helicopters, unmanned airborne vehicles, and aerostats.[66]

In July 2024, Reliance Industries was granted the approval by United States to resume importing oil from Venezuela.[67]

The company had more than 200 subsidiary companies and more than 15 associate companies as of 2024.[68][69] In fiscal year 2024, the company generated 65% of its sales in India and 35% outside India.[65]

Financials
Year	2010[70]	2011[70]	2012[70]	2013[70]	2014[70]	2015[71]	2016[72]	2017[73]	2018[74]	2019[75]	2020[76]
Revenue (₹ cr)	2,00,400	2,58,651	3,39,792	3,71,119	4,01,302	3,88,494	2,96,091	3,30,180	4,30,731	6,25,212	6,59,205
Profit after tax (₹ cr)	16,236	20,286	20,040	21,003	21,984	23,566	27,630	29,901	34,993	39,837	44,324
Year	2021[76]	2022[77]	2023[77]	2024[77]	2025[78]
Revenue (₹ cr)	5,39,238	7,88,743	9,74,864	10,00,122	10,71,174
Profit after tax (₹ cr)	53,739	66,184	73,670	79,020	81,309
Subsidiaries
Jio Platforms
Main article: Jio Platforms
Jio Platforms Limited, essentially a technology company, is a majority-owned subsidiary of RIL. It has a valuation of more than US$100 billion on expert view as of October 2022. It is the result of a corporate restructuring announced in October 2019, resulting in all the digital initiatives and the telecommunication assets being housed under this new subsidiary.[79] This new subsidiary holds all the digital business assets including Reliance Jio Infocomm Ltd, which in turn holds the Jio connectivity business - mobile, broadband and enterprise, and also the other digital assets (Jio Apps, Tech backbone and Investments in other tech entities like Haptic, Hathway and Den Networks among others).[80] In April 2020, RIL announced a strategic investment of ₹43,574 crore (US$5.88 billion) by Facebook into Jio Platforms. This investment translated into a 9.99% equity stake, on a fully diluted basis.[81][non-primary source needed] Further in May 2020, RIL sold roughly 1.15% stake in Jio Platforms for ₹5,656 crore (US$763.3 million) to the American private equity investor, Silver Lake Partners.[82] Intel became the 12th company to invest in Reliance Jio platforms after it invested ₹1,894.50 crore ($250 million), the total investments in Jio platforms is ₹117,588.45 crore so far.[83] On 16 July 2020, Google announced that it will acquire a 7.7% stake in Jio Platforms for ₹33,737 crore (US$5.02 billion).[84] Mukesh Ambani has named his son, Akash Mukesh Ambani as the chairperson of Jio in 2022.[85]

Reliance Retail
Main article: Reliance Retail
Reliance Retail is the retail business wing of the Reliance Industries. In March 2013, it had 1466 stores in India.[86][non-primary source needed] It is the largest retailer in India.[87] Many brands like Reliance Fresh, Reliance Footprint, Reliance Time Out, Reliance Digital, Reliance Wellness, Reliance Trends, Reliance Autozone, Reliance Super, Reliance Mart, Reliance iStore, Reliance Home Kitchens, Reliance Market (Cash n Carry) and Reliance Jewel come under the Reliance Retail brand. Its annual revenue for the financial year 2012–13 was ₹108 billion (US$1.3 billion) with an EBITDA of ₹780 million (US$9.2 million). Its market value is more than $60 billion.[88][non-primary source needed][89] Mukesh Ambani stepped down from the position of chairperson of Reliance Retail and handed over the job to his daughter Isha Ambani Piramal.[90] Ambani announced it during the 45th Reliance AGM, in 2022. As per reports, this act is a part of Ambani's leadership transition.[91]

Reliance Industrial Infrastructure
Main article: Reliance Industrial Infrastructure
Reliance Industrial Infrastructure Limited (RIIL) is an associate company of RIL. It was incorporated in September 1988 as Chembur Patalganga Pipelines Limited, with the main objective being to build and operate cross-country pipelines for transporting petroleum products. The company's name was subsequently changed to CPPL Limited in September 1992, and thereafter to its present name, Reliance Industrial Infrastructure Limited, in March 1994.[92] RIIL is mainly engaged in the business of setting up and operating industrial infrastructure. The company is also engaged in related activities involving leasing and providing services connected with computer software and data processing.[93][non-primary source needed]

Network18 Group
Main article: Network18 Group
Between 2011 and 2014, Reliance acquired majority stake in Network18 Group. Through Network18, Reliance owns multiple news channels including CNN-News18 and News18 India.[94]

Network 18 is a mass media company. It has interests in television, digital platforms, publication, mobile apps and films. It also operates two joint ventures, namely Viacom18 and History TV18 with Viacom and A+E Networks respectively. It has also acquired a partial part of ETV Network and since renamed its channels under the Colors TV brand.[citation needed]

Other
Reliance Global Corporate Security is a private security company founded in 17 August 1998. It provides enterprise wide security to assets of Reliance Industries. It is composed of former member of the military and paramilitary forces, law enforcement agencies, intelligence services as well as technical experts from other industries.[95][96]
Reliance Life Sciences works around medical, plant and industrial biotechnology opportunities. It specialises in manufacturing, branding, and marketing Reliance Industries' products in bio-pharmaceuticals, pharmaceuticals, clinical research services, regenerative medicine, molecular medicine, novel therapeutics, biofuels, plant biotechnology, and industrial biotechnology sectors of the medical business industry.[97]
Embibe a Bengaluru-based EdTech start-up raised funding of ₹89.91 crores from RIL in February 2020. Over three years, Reliance Industries had invested around $180 million in the start-up. A part of it was towards acquiring a stake of 72.69% from Embibe's existing investors. In December 2019, Embibe, under the proprietary name (Individual Learning Private Limited), announced that it picked up equity shares in Bengaluru-based K12 startup Funtoot (eDreams Edusoft). The deal was capped at ₹71.64 crores in cash, which holds 90.5% of the equity share capital of Funtoot. In February 2020, it acquired the rival platform OnlineTyari.[98][99]
Reliance Logistics is a single-window[clarification needed] company selling transportation, distribution, warehousing, logistics, and supply chain-related products.[100][101][non-primary source needed][102] Reliance Logistics is an asset based company with its own fleet and infrastructure.[103] It provides logistics services to Reliance group companies and outsiders.[104]
Reliance Solar, the solar energy subsidiary of Reliance, was established to produce and retail solar energy systems primarily to remote and rural areas. It offers a range of products based on solar energy: solar lanterns, home lighting systems, street lighting systems, water purification systems, refrigeration systems and solar air conditioners.[105][non-primary source needed] In 2022 RIL AGM, Mukesh Ambani specified that his youngest son Anant Ambani will take over the new energy business.[106]
Reliance Eros Productions LLP, joint venture with Eros International to produce film content in India.[107]
Reliance Industrial Investments and Holdings Limited (RIIHL), a wholly owned subsidiary of RIL which provides financial services. The Company owns securities of companies other than banks, as well as offers investment services.[108] RIIHL bought majority stakes in two companies - logistics firm Grab A Grub Services Private Limited and software company C-Square Info Solutions - for over ₹146 crores in March 2019. RIIHL also sponsored the Tower Investment trust (InvITs) for the acquisition of 49% equity in RJio's tower assets for ₹25,215 crores by the Canadian asset management firm Brookfield Infrastructure Partners.[109] On 22 April 2021, RIIHL acquired the entire issued share capital of Stoke Park Ltd, company that owns and manages sporting and leisure facilities in Stoke Poges, Buckinghamshire for £57 million.[110]
Reliance Strategic Business Ventures Limited (RSBVL), a wholly owned subsidiary of RIL bought a 51.78% stake in robotics and AI firm Asteria Aerospace for ₹23.12 crore and an 85% stake in NowFloats Technologies for ₹141.63 crores in Dec 2019.[111] It also holds 18.83% in EIH Limited, the flagship company of The Oberoi Group, one of the largest luxury hotel chains in India. In November 2019, RSBVL invested an undisclosed amount in SkyTran Inc. for 12.7%, increased it further to 26.3% by April 2020. In February 2021, RIL became the majority stakeholder with 54.46% with an additional investment of $26.76 million.[112]
Reliance Sibur is a joint venture between Reliance Industries and Silbur in the business of making synthetic rubber.[113][non-primary source needed]
Relicord is a cord blood banking service owned by Reliance Life Sciences. It was established in 2002.[114][non-primary source needed] It has been inspected and accredited by AABB,[115] and also has been accorded a licence by Food and Drug Administration (FDA), Government of India.
Reliance Institute of Life Sciences (RILS), established by Dhirubhai Ambani Foundation, is an institution offering higher education in various fields of life sciences and related technologies.[116][non-primary source needed][117]
Reliance Clinical Research Services (RCRS), a contract research organisation (CRO) and wholly owned subsidiary of Reliance Life Sciences, specialises in the clinical research services industry. Its clients are primarily pharmaceutical, biotechnology and medical device companies.[118][non-primary source needed]
LYF, a 4G-enabled VoLTE device brand from Reliance Retail.[119]
Indiawin Sports Pvt. Ltd. is a 100% subsidiary that owns the Mumbai Indians men's and women's professional T20 franchise cricket teams, playing in the IPL and WPL respectively. Besides, they also own various teams across different leagues globally such as the MI Cape Town, MI Emirates, MI New York teams in the SA20, ILT20 and the MLC leagues respectively.
Former holdings
In March 2017, Reliance Industries Ltd (RIL) completed the sale process of its 76% equity stake in Mauritius-based oil retailer Gulf Africa Petroleum Corp (GAPCO) to Total Marketing & Services, a subsidiary of the French oil and gas firm Total SE.[120]

The East West Pipeline has been acquired by India Infrastructure Trust, which is owned by Brookfield Asset Management, for a consideration of ₹13,000 crore.[121]

Criticism and controversies
The company has attracted controversy for reports of political corruption, cronyism, fraud, financial manipulation, and exploitation of its customers, Indian citizens, and natural resources.[12][122][14][15][16] The chairman of Reliance Industries, Mukesh Ambani, has been described as a plutocrat.[123]

ONGC litigation
In May 2014, ONGC complained to the Delhi High Court accusing RIL of pilferage of 18 billion cubic metres of gas from its gas-producing block in the Krishna Godavari basin.[124] Subsequently, the two companies agreed to form an independent expert panel to probe any pilferage.[125]

Cronyism
Seminar magazine (2003) detailed Reliance founder Dhirubhai Ambani's proximity to politicians, his enmity with Bombay Dyeing's Nusli Wadia, the exposes by the Indian Express and Arun Shourie about illegal imports by the company and overseas share transactions by shell companies, and the botched attempt to acquire Larsen & Toubro.[126]

As early as 1996, Outlook magazine addressed other controversies related to fake and switched shares; insider trading; and a nexus with the state-owned Unit Trust of India. Five main allegations concerning Reliance, which have plunged the Indian capital markets into a period of uncertainty unsurpassed since the days of the securities scam were:

Reliance issued fake shares.
It switched shares sent for transfer by buyers to make illegal profits.
It indulged in insider trading in shares.
It established a nexus with the Unit Trust of India to raise huge sums of money to the detriment of UTI subscribers.
It attempted to monopolize the private telecom services market through front companies.[12]
2005 Criminal investigation
The Central Bureau of Investigation (CBI) filed a charge sheet in a Mumbai court against Reliance Industries Limited (RIL) and four retired employees of National Insurance Company Limited (NICL), including a former CMD, under provisions of the Prevention of Corruption Act for criminal conspiracy and other charges. Acting on a reference from CVC in March 2005, the CBI started probing the conspiracy that led to the filing of the charge sheet on 9 December 2011. The 2005 complaint had alleged irregularities in the issuance of insurance policies — for coverage of default payments — by NICL to RIL. The charge sheet also mentioned criminal offenses with dishonest intention and causing wrongful loss totaling ₹147.41 crores to NICL and wrongful gain to the private telecom provider.[14]

Two retired senior officials of National Insurance Company Limited and 11 others were awarded varying jail terms by a Delhi court in Jan 2014.[127]

RIL plane grounded
A business jet owned by Reliance Industries (RIL) was grounded by The Directorate General of Civil Aviation (DGCA) on 22 March 2014 during a surprise inspection, for carrying expired safety equipment on board; its pilot was also suspended for flying without a license.[128]

Krishna Godavari (KG) Basin gas controversy
Reliance Industries Limited (RIL) was supposed to relinquish 25% of the total area outside the discoveries in 2004 and 2005, as per the Production Sharing Contract (PSC). However, the entire block was declared as a discovery area and RIL was allowed to retain it. In 2011, the Comptroller and Auditor General of India (CAG) criticized the Oil Ministry for this decision. The CAG also faulted RIL for limiting the competition in contracts, stating that RIL awarded a $1.1 billion contract to Aker on a single-bid basis.[15][129]

Petition against Reliance Jio
A PIL filed in the Supreme Court by an NGO Centre for Public Interest Litigation, through Prashant Bhushan, challenged the grant of a pan-India license to RJIL by the Government of India. The PIL alleged that RJIL was allowed to provide voice telephony along with its 4G data service, by paying an additional fee of just INR 16,580 million (US$280 million) which was arbitrary and unreasonable and contributed to a loss of INR 228,420 million (US$3.8 billion) to the exchequer.[130][131]

The CAG in its draft report alleged rigging of the auction mechanism, whereby an unknown ISP, Infotech Broadband Services Pvt Ltd, acquired the spectrum by bidding 5000 times its net worth, after which the company was sold to Reliance Industries.[132]

Future Retail deal and possession
In February 2022, Reliance terminated the leases of hundreds of Future Retail locations, the next largest retail chain in India, and took possession of those brick-and-mortar shops. Future Retail had a deal to sell its assets to Reliance, but that deal was contested by Amazon.com, which in 2019 acquired a stake in a subunit of Future Retail along with certain rights with respect to the transfer of the retailer's assets. Reliance's possessions came after rounds of legal wrangling, including a 2020 arbitration in Singapore and an antitrust review by the Competition Commission of India.[133][134][135][136]

Stock manipulation and penalty
For manipulating shares of Reliance Petroleum Limited (RPL), Reliance Industries was fined Rs. 950 crore (about 447 crore in retracted gains and 500 crore in interest) in 2007.[16] In April 2006, RPL went public as a Reliance subsidiary at a price of Rs. 60 per share. The market crashed by 30% after it floated at roughly Rs. 100, and RPL was back at 60. In accordance with Securities and Exchange Board of India directive, RIL carried out an organised operation with the help of its agents in order to obtain unauthorised profits from the trading of its formerly listed unit, RPL, which was combined with the former in 2009.[137][138][139][140][141]

Reliance's business ties with Russia
Reliance Industries has faced criticism for maintaining business relations with Russia despite international sanctions imposed following Russia’s invasion of Ukraine in 2022. The company has engaged in energy deals with Russian oil giant Rosneft, raising concerns about its alignment with global efforts to reduce economic ties with Russia. Reliance has been listed on Leave Russia, a platform tracking companies still active in the Russian market, further intensifying scrutiny over its role in facilitating Russian energy exports.[142][143] In December 2024, Reliance Industries entered into a contract with Rosneft to procure 500,000 barrels of oil per day for 10 years. This corresponds to around US$13 billion per year.[144]

Reliance demerger and family feud
The Ambani family holds around 45% of the shares in RIL.[145] Since its inception, the company was managed by its founder and chairman Dhirubhai Ambani. After suffering a stroke in 1986, he handed over the daily operations of the company to his sons Mukesh Ambani and Anil Ambani. After the death of Dhirubhai Ambani in 2002, the management of the company was taken up by both the brothers. In November 2004, Mukesh Ambani, in an interview, admitted to having differences with his brother Anil over 'ownership issues'.[146] He also said that the differences "are in the private domain". The share prices [147] of RIL were impacted by some margin when this news broke out. In 2005, after a bitter public feud between the brothers over the control of the Reliance empire, mother Kokilaben intervened to broker a deal splitting the RIL group business into two parts.[148] In October 2005, the split of Reliance Group was formalised. Mukesh Ambani got Reliance Industries and IPCL. Younger brother Anil Ambani received telecom, power, entertainment, and financial services business of the group. The Anil Dhirubhai Ambani Group includes Reliance Communications, Reliance Infrastructure, Reliance Capital, Reliance Natural Resources and Reliance Power.[149][150]

The division of Reliance group business between the two brothers also resulted in de-merger of 4 businesses from RIL.[151][152] These businesses immediately became part of Anil Dhirubhai Ambani Group. The existing shareholders in RIL, both the promoter group and non-promoters, received shares in the de-merged companies.[32]

Awards and recognition
International Refiner of the year in 2017 at Global Refining and Petrochemicals Congress 2017 [153]
International Refiner of the Year in 2013 at the HART Energy's 27th World Refining & Fuel Conference. This is the second time that RIL has received this Award for its Jamnagar Refinery, the first being in 2005.[154]
The Brand Trust Report ranked Reliance Industries as the 7th most trusted brand in India in 2013 and 9th in 2014.[155][156]
RIL was certified as 'Responsible Care Company' by the American Chemistry Council in March 2012.[157]
RIL was ranked at 25th position across the world, on the basis of sales, in the ICIS Top 100 Chemicals Companies list in 2012.[158]
RIL was awarded the National Golden Peacock Award 2011 for its contribution in the field of corporate sustainability.[159]
In 2009, Boston Consulting Group (BCG) named Reliance Industries as the world's fifth biggest 'sustainable value creator' in a list of 25 top companies globally in terms of investor returns over a decade.[160]
The company was selected as one of the world's 100 best managed companies for the year 2000 by IndustryWeek magazine.[19][161]
From 1994 to 1997, the company won National Energy Conservation Award in the petrochemical sector.[19]
See also
	Companies portal
flag	India portal
List of companies of India
Dhirubhai Ambani Green Energy Giga Complex
Reliance Group
Dhirubhai Ambani
References
 "Reliance Industries Limited | Business, Leadership, & History | Britannica". www.britannica.com. 7 July 2023. Archived from the original on 26 May 2022. Retrieved 30 January 2023.
 "Stock Share Price | Get Quote | BSE". www.bseindia.com. Archived from the original on 29 January 2023. Retrieved 29 January 2023.
 "Reliance Industries AR 2023-24" (PDF). Archived from the original (PDF) on 8 August 2024. Retrieved 8 August 2024.
 "Financial Results Presentation FY 2024-25 / 4Q FY2025" (PDF). ril.com. Reliance Industries Limited. Archived (PDF) from the original on 26 April 2025. Retrieved 26 April 2025.
 "Consolidated and Standalone financial results for the quarter and year ended March 31, 2025" (PDF). ril.com. Reliance Industries Limited. Archived (PDF) from the original on 5 May 2025. Retrieved 26 April 2025.
 "Top '100' companies by market capitalisation as on July 19, 2017". Bseindia.com. Archived from the original on 15 July 2017. Retrieved 20 July 2017.
 "Top 10 Companies In India By Market Valuation In 2025". Forbes India. Archived from the original on 23 April 2025. Retrieved 6 April 2025.
 "RIL becomes India's biggest company in revenue terms". The Economic Times. 21 May 2019. Archived from the original on 4 January 2020. Retrieved 21 May 2019.
 "Fortune Global 500 list". Archived from the original on 7 August 2019. Retrieved 10 August 2022.
 "Reliance Industries Consolidated Balance Sheet, Reliance Industries Financial Statement & Accounts". ClearTax. Archived from the original on 3 July 2023. Retrieved 30 June 2020.
 "Reliance Industries AGM full text". 21 July 2017. Archived from the original on 6 August 2017. Retrieved 21 July 2017.
 "Blind Ambition". Outlookindia.com/. Archived from the original on 14 June 2018. Retrieved 26 August 2018.
 "Outlook India Magazine: India's Best Online News Magazine for In-depth News, Analysis, Opinion". Archived from the original on 28 April 2023. Retrieved 24 July 2023.
 "NICL scam: CBI files charges against Reliance Industries Limited, 4 retired insurance firm employees". The Times of India. Archived from the original on 10 July 2018. Retrieved 26 August 2018.
 "CAG flays Oil Min for allowing RIL to retain D6 area". India Today. 8 September 2011. Archived from the original on 5 January 2018. Retrieved 26 August 2018.
 Scroll Staff (2 January 2021). "SEBI fines Reliance Industries, Mukesh Ambani Rs 40 crore for 'manipulative trades' in 2007". Scroll.in. Archived from the original on 29 January 2023. Retrieved 29 January 2023.
 "Meet Asia's millennial plutocrats". The Economist. Archived from the original on 23 July 2023. Retrieved 24 July 2023.
 "Ambani: From a gas station attendant to Reliance owner". Arab News. 2 November 2012. Archived from the original on 24 August 2013. Retrieved 26 August 2013.
 "Company History – Reliance Industries Ltd". The Economic Times. Archived from the original on 28 September 2013. Retrieved 26 August 2013.
 "Major Milestones". RIL.com. Archived from the original on 17 August 2013. Retrieved 22 August 2013.
 "Reliance Industries: Milestones of an oil giant – Slide 4". NDTV.com. Archived from the original on 28 September 2013. Retrieved 25 August 2013.
 Com, Ril. "Our History – Reliance Industries". Archived from the original on 9 December 2023. Retrieved 26 August 2013.
 "Reliance Industries Ltd". HDFC Securities. Archived from the original on 10 January 2014. Retrieved 26 August 2013.
 "Reliance Industries: Milestones of an oil giant – Slide 8". NDTV.com. Archived from the original on 2 October 2013. Retrieved 25 August 2013.
 "Reliance Industries: Milestones of an oil giant – Slide 9". NDTV.com. Archived from the original on 2 October 2013. Retrieved 25 August 2013.
 "Krishna-Godavari basin to yield 160mt oil: RIL". The Economic Times. 1 November 2002. Archived from the original on 10 January 2014. Retrieved 25 August 2013.
 "Reliance makes it big with IPCL". The Hindu. 20 May 2002. Archived from the original on 14 April 2012. Retrieved 25 August 2013.
 "Ministry of Environment Forest and Climate Change Government of India" (PDF). April 2017. Archived (PDF) from the original on 28 July 2018. Retrieved 4 May 2020.
 Nina Muncherji, C. Gopalakrishnan, Upider Dhar (2009). Partners In Success: Strategic Hr And Entrepreneurship. Excel Books India. p. 6. ISBN 9788174467010.
 "IPCL set to merge with Reliance Industries". Business Standard. 8 March 2007. Archived from the original on 10 January 2014. Retrieved 25 August 2013.
 "Reliance-IPCL merger swap ratio set at 1:5". The Financial Express. 11 March 2007. Archived from the original on 10 January 2014. Retrieved 25 August 2013.
 "Scheme of Demerger". RIL.com. Archived from the original on 9 May 2013. Retrieved 25 August 2013.
 "BTvIn - Retail: Growth Engine For RIL". Btvin. Archived from the original on 8 December 2014. Retrieved 26 June 2014.
 "Reliance launches retail venture". BBC News. 3 November 2006. Archived from the original on 10 January 2014. Retrieved 25 August 2013.
 "Coming to your neighbourhood – Reliance Fresh". Business Standard. 3 November 2006. Archived from the original on 10 January 2014. Retrieved 25 August 2013.
 https://www.financialexpress.com/archive/high-realty-prices-no-deterrent-for-reliance-retail-expansion/336528/
 "RIL shareholders approve 1:1 bonus issue". 19 November 2009 – via The Economic Times - The Times of India.
 "Reliance Industries board approves 1:1 bonus issue for shareholders". 5 September 2024 – via The Economic Times - The Times of India.
 "Reliance Bets Big on 4G". The Wall Street Journal. 12 June 2010. Archived from the original on 18 March 2015. Retrieved 25 August 2013.
 "Reliance Industries to acquire Infotel Broadband". The Hindu. 11 June 2010. Archived from the original on 10 January 2014. Retrieved 25 August 2013.
 "BP partners Reliance in $7.2 billion Indian oil hunt". Reuters India. 22 February 2011. Archived from the original on 10 January 2014. Retrieved 25 August 2013.
 "Reliance Industries, BP complete $7.2-billion deal". The Economic Times. 31 August 2011. Archived from the original on 8 September 2013. Retrieved 25 August 2013.
 "RIL, Russia's Sibur join hands for Jamnagar butyl rubber unit". The Economic Times. Archived from the original on 10 September 2017. Retrieved 19 July 2017.
 Carter, J. and Chalk, E., A reliable decision: foreign act of state doctrine applies in English arbitration, DLA Piper published on 15 July 2018, accessed on 8 July 2025
 "Fynd - Your Everyday Fashion Destination". Fynd. Archived from the original on 7 July 2022. Retrieved 29 June 2022.
 Bloomberg (5 August 2019). "Reliance to buy Google-backed tech start-up Shopsense Retail". @businessline. Archived from the original on 12 July 2020. Retrieved 9 July 2020.
 "Reliance-Shopsense Deal" (PDF). RIL.com. 2 August 2019. Archived from the original (PDF) on 27 April 2022. Retrieved 1 March 2024.
 "Top 100 stocks by Market Capitalization | BSE Listed stocks Market Capitalization". www.bseindia.com. Archived from the original on 25 July 2019. Retrieved 19 December 2022.
 "AI model backed by Mukesh Ambani's Reliance Industries to launch in March". Business Standard. Archived from the original on 24 February 2024. Retrieved 25 February 2024.
 Goldsmith, Jill (28 February 2024). "Disney And Reliance Clinch Joint Venture In India". Deadline Hollywood. Archived from the original on 28 February 2024. Retrieved 28 February 2024.
 "Reliance and Disney announce strategic joint venture to bring together the most compelling and engaging entertainment brands in India" (PDF). BSE India. Archived from the original (PDF) on 28 February 2024. Retrieved 3 April 2025.
 Manfredi, Lucas (14 November 2024). "Disney, Reliance Industries Close $8.5 Billion Merger of Star India and Viacom18". TheWrap. Archived from the original on 15 November 2024. Retrieved 18 November 2024.
 "Nvidia to supply chips to Reliance, other Indian companies in AI push". Reuters. 24 October 2024.
 Pubby, Manu (3 June 2025). "Indigenous artillery ammo nears completion". The Economic Times. ISSN 0013-0389. Archived from the original on 21 July 2025. Retrieved 21 June 2025.
 "Reliance Industries >> Shareholding Pattern - March 2017". www.nseindia.com. Archived from the original on 20 July 2017. Retrieved 20 July 2017.
 "Reliance Industries shareholdings: Find Reliance Industries Shareholding Pattern and Ownership". www.livemint.com. Archived from the original on 2 September 2023. Retrieved 2 September 2023.
 "Reliance Industries buyback: Beyond face value". The Indian Express. 18 January 2013. Archived from the original on 28 March 2020. Retrieved 24 August 2013.
 "Investors' Handbook". Ril.com. Archived from the original on 17 August 2013. Retrieved 15 August 2013.
 "Reliance Industries Ltd. – Listing". The Economic Times. Archived from the original on 7 October 2013. Retrieved 25 August 2013.
 "Listing Information". RIL.com. Archived from the original on 26 May 2013. Retrieved 26 August 2013.
 "Credit Ratings". RIL.com. Archived from the original on 21 July 2013. Retrieved 26 August 2013.
 "S&P raises credit rating on RIL to 'BBB+'". Reuters India. 29 May 2013. Archived from the original on 28 February 2014. Retrieved 26 August 2013.
 "Rating Action: Moody's assigns definitive Baa2 rating to Reliance's USD senior unsecured perpetual notes". Moody's. 31 January 2013. Archived from the original on 3 April 2015. Retrieved 26 August 2013.
 "'White knight' Mukesh's RJio to buy RCom's wireless assets". Business Line. 28 December 2017. Archived from the original on 1 March 2024. Retrieved 26 August 2018.
 "Reliance Industries Ltd: Business Segments and Geographical Breakdown of Revenue". www.marketscreener.com. Archived from the original on 18 February 2025. Retrieved 9 May 2025.
 "RIL lines up close to $1 billion plan in aerospace sector, may hire around 1,500 people". The Times of India. 28 July 2012. Archived from the original on 29 July 2012. Retrieved 26 August 2013.
 "India's Reliance gets US nod to import oil from Venezuela, source says". Reuters. Retrieved 24 July 2024.
 "Reliance Industries Limited : List of subsidiaries" (PDF). India Ratings. Archived (PDF) from the original on 24 July 2024. Retrieved 24 July 2024.
 "Major Subsidiaries & Associates". 31 March 2023. Archived from the original on 21 April 2024. Retrieved 21 April 2024.
 Reliance Industries Annual Report 2014 (PDF)
 Reliance Industries Annual Report 2015 Archived 21 February 2025 at the Wayback Machine (PDF)
 Reliance Industries Annual Report 2016 (PDF)
 Reliance Industries Annual Report 2017 Archived 21 February 2025 at the Wayback Machine (PDF)
 Reliance Industries Annual Report 2018 Archived 12 November 2022 at the Wayback Machine (PDF)
 Reliance Industries Annual Report 2019 Archived 21 February 2025 at the Wayback Machine (PDF)
 Reliance Industries Annual Report 2021 Archived 21 February 2025 at the Wayback Machine (PDF)
 Reliance Industries Annual Report 2023-24 Archived 25 May 2025 at the Wayback Machine (PDF)
 Financial Results Presentation FY 2024-25 / 4Q FY2025 Archived 26 April 2025 at the Wayback Machine (PDF)
 "RIL's new digital unit christened Jio Platforms Ltd". @businessline. 29 November 2019. Archived from the original on 3 February 2021. Retrieved 5 May 2020.
 Pathak, Kalpana (26 October 2019). "Rejig of group structure at RIL paves way for Jio stake sale". Livemint. Archived from the original on 1 December 2019. Retrieved 5 May 2020.
 "Facebook to Invest ₹ 43,574 Crore in JIO Platforms for a 9.99% Stake. Largest FDI for Minority Investment in India. Partnership to Create Opportunities for eople and Businesses" (Press release). Mumbai. Reliance Industries Limited. Archived from the original on 24 April 2020. Retrieved 5 May 2020.
 "Reliance sells 1.15% stake in Jio Platforms to PE firm for Rs 5,656 crore". Hindustan Times. 5 May 2020. Archived from the original on 5 May 2020. Retrieved 5 May 2020.
 Mishra, Lalatendu (3 July 2020). "Intel Capital to buy 0.39% stake in Jio Platforms for ₹1,894 crore". The Hindu. ISSN 0971-751X. Archived from the original on 4 July 2020. Retrieved 8 July 2020.
 "Google to invest Rs 33,737 crore for a 7.7 per cent stake in Jio Platforms". The Economic Times. Archived from the original on 17 January 2021. Retrieved 16 July 2020.
 Haraito, Gloria. "Mukesh Ambani Flags Off Succession, Anointing Son Akash Ambani Chairman Of Reliance Jio Infocomm". Forbes. Archived from the original on 10 October 2022. Retrieved 10 October 2022.
 "Financial Presentation of 2012–13 Q4 Results" (PDF). RIL.com. 16 April 2013. Archived from the original (PDF) on 3 April 2015. Retrieved 27 August 2013.
 "Ambani tops retailer list, too". Business Standard. 17 August 2013. Archived from the original on 10 January 2014. Retrieved 19 August 2013.
 "Annual Report 2012-13" (PDF). RIL.com. 8 May 2013. Archived from the original (PDF) on 16 October 2013.
 "Few RIL retail arms still making losses". Business Standard. 11 May 2013. Archived from the original on 26 June 2014. Retrieved 27 August 2013.
 Sanjai, P. R. (29 June 2022). "Mukesh Ambani's daughter Isha Ambani to be named chair of Reliance retail". ThePrint. Archived from the original on 10 October 2022. Retrieved 10 October 2022.
 "Reliance in process of momentous leadership transition, says Mukesh Ambani". India Today. 29 December 2021. Archived from the original on 10 October 2022. Retrieved 10 October 2022.
 Com. "Company History". Archived from the original on 28 April 2014. Retrieved 22 August 2013.
 "About us". RIIL.in. Archived from the original on 28 December 2009. Retrieved 18 August 2013.
 Bhula, Pooja (19 July 2023). "Who Owns Your Media: Network18's journey from a production house to a broadcast behemoth". Newslaundry. Archived from the original on 7 May 2024. Retrieved 21 April 2024.
 "Former Indian military personnel to guard Reliance Industries' assets". The Hindu. 19 February 2016. ISSN 0971-751X. Archived from the original on 4 April 2023. Retrieved 29 March 2023.
 "About Reliance Global Corporate Security", Defence Guru India, archived from the original on 30 March 2023, retrieved 30 March 2023
 "Changing its DNA". Business Today. 30 September 2012. Archived from the original on 1 December 2012. Retrieved 26 August 2013.
 "Reliance Industries: RIL-backed firm Embibe gets 91% stake in Funtoot". The Economic Times. Archived from the original on 24 April 2021. Retrieved 24 April 2021.
 "Mukesh Ambani doubles his bet on edtech – Reliance Industries invests ₹500 crore in startup Embibe". Business Insider. Archived from the original on 24 April 2021. Retrieved 24 April 2021.
 "Company Overview of Reliance Logistics Private Limited". Bloomberg BusinessWeek. Archived from the original on 28 June 2013. Retrieved 27 August 2013.
 "About us, Reliance Logistics". Reliancelogistics.com. Archived from the original on 21 November 2010. Retrieved 18 August 2013.
 "Reliance in deal with CONCOR for logistics venture". 25 September 2007. Archived from the original on 27 August 2013. Retrieved 27 August 2013.
 "Reliance Logistics Ltd". Supplychainleaders.com. Archived from the original on 28 February 2014. Retrieved 27 August 2013.
 "Reliance set to combine two logistics arms". Financial Chronicle. 31 March 2009. Archived from the original on 30 January 2016. Retrieved 27 August 2013.
 "About us, Reliance Solar". Relsolar.com. Archived from the original on 11 September 2013. Retrieved 18 August 2013.
 "Mukesh Ambani's youngest son Anant to lead new energy sector at Reliance". Hindustan Times. 29 August 2022. Archived from the original on 10 October 2022. Retrieved 10 October 2022.
 "Mukesh Ambani's Reliance Industries Takes Stake in Eros International". 20 February 2018. Archived from the original on 4 November 2018. Retrieved 3 November 2018.
 "Reliance Industrial Investments & Holdings Ltd - Company Profile and News". Bloomberg.com. Archived from the original on 24 April 2021. Retrieved 24 April 2021.
 Kurup, Rajesh (28 August 2020). "RJio gets approval for Brookfield deal from DoT, SEBI". @businessline. Archived from the original on 24 April 2021. Retrieved 24 April 2021.
 Barman, Arijit. "Mukesh Ambani buys Britain's iconic country club Stoke Park for 57 million pounds". The Economic Times. Archived from the original on 24 April 2021. Retrieved 24 April 2021.
 "RIL to continue acquisition spree in 2021". @businessline. 7 March 2021. Archived from the original on 24 April 2021. Retrieved 24 April 2021.
 www.ETEnergyworld.com. "Reliance Industries acquires majority equity stake in skyTran Inc - ET EnergyWorld". ETEnergyworld.com. Archived from the original on 24 April 2021. Retrieved 24 April 2021.
 "Reliance Sibur". www.reliancesibur.com. Archived from the original on 10 December 2023. Retrieved 1 March 2024.
 "About us, Relicord". Relicord.com. Archived from the original on 12 August 2013. Retrieved 18 August 2013.
 "AABB Accredited Cord Blood (CB) Facilities". AABB.org. Archived from the original on 2 May 2014. Retrieved 18 August 2013.
 "Welcome to Reliance Institute of Life Sciences". RILS.com. Archived from the original on 8 August 2013. Retrieved 18 August 2013.
 "Reliance Institute of Life Sciences". Minglebox.com. Archived from the original on 19 August 2014. Retrieved 26 August 2013.
 "Clinical Research Services (CRS) group of Reliance Life Sciences". RelLife.com. Archived from the original on 20 October 2013. Retrieved 18 August 2013.
 "LYF Smartphones - Its All About Your Lifestyle". MyLYF. Archived from the original on 6 March 2016. Retrieved 1 March 2016.
 "Reliance Industries Ltd sells its 76% stake in Gulf Africa Petroleum to Total". The Financial Express. 29 March 2017. Archived from the original on 24 April 2021. Retrieved 24 April 2021.
 Market, Capital (15 March 2019). "Brookfield sponsored India Infrastructure Trust to acquire East-West Pipeline for Rs. 13,000 cr". Business Standard India. Archived from the original on 25 July 2023. Retrieved 10 March 2021.
 Outlook Web Desk (29 January 2022). "A History Of Controversies". Outlook India. Archived from the original on 28 April 2023. Retrieved 20 March 2024.
 "Meet Asia's millennial plutocrats". The Economist. Archived from the original on 23 July 2023. Retrieved 24 July 2023.
 "Independent panel to probe discrepancies in Krishna-Godavari Basin". Hindustan Times. Archived from the original on 31 May 2014. Retrieved 30 May 2014.
 "Independent panel to probe discrepancies in Krishna-Godavari Basin". News.biharprabha.com. Archived from the original on 31 May 2014. Retrieved 30 May 2014.
 "521 Raranjoy Guha Thakurta, the two faces of Dhirubhai Ambani". Archived from the original on 10 January 2018. Retrieved 15 April 2018.
 "NICL scam: 13 sentenced to jail". Business Standard. Press Trust of India. 24 January 2014. Archived from the original on 17 June 2018. Retrieved 26 August 2018.
 Reliance Industries#cite note-80
 "Reliance violated contract terms in KG Basin, finds CAG report". The Financial Express. 9 September 2011. Archived from the original on 31 October 2014. Retrieved 26 August 2018.
 "Petition against 4G licence to Reliance Jio: Apex court seeks Centre's reply". Business Line. 9 May 2014. Archived from the original on 11 May 2014. Retrieved 26 August 2018.
 "Reliance Jio goes for the kill". Rediff.com. Archived from the original on 28 September 2018. Retrieved 26 August 2018.
 "DoT refutes CAG's charges of favouring Reliance Jio by allowing it to convert its ISP permit into a unified license - Economic Times". Archived from the original on 7 July 2014. Retrieved 4 July 2014.
 "Too bad for Amazon, Mukesh Ambani's Reliance has seized the future of retail in India". ThePrint. 16 March 2022. Archived from the original on 27 March 2022. Retrieved 27 March 2022.
 Roy, Abhirup; Kalra, Aditya (16 March 2022). "Explainer: Amazon's battle with Reliance for India retail supremacy". Reuters. Archived from the original on 27 March 2022. Retrieved 27 March 2022.
 "'Shops gone': How RIL stunned Amazon in battle for Future Retail". The Indian Express. 7 March 2022. Archived from the original on 27 March 2022. Retrieved 27 March 2022.
 Kalra, Aditya; Roy, Abhirup (15 March 2022). "After talks with India's Future fail, Amazon goes on the attack in newspaper ads". Reuters. Archived from the original on 27 March 2022. Retrieved 27 March 2022.
 "Reliance Petroleum case | SEBI fines Reliance Industries, Mukesh Ambani, two other entities". The Hindu. 1 January 2021. Archived from the original on 29 January 2023. Retrieved 29 January 2023 – via www.thehindu.com.
 Pathak, Kalpana (1 January 2021). "RPL case: Sebi slaps fine on Reliance, Ambani". mint. Archived from the original on 29 January 2023. Retrieved 29 January 2023.
 "SEBI imposes penalty on Mukesh Ambani and Reliance Industries for manipulative trading". Business Insider. Archived from the original on 29 January 2023. Retrieved 29 January 2023.
 "India's Reliance Industries and chairman fined over share trades". Reuters. 1 January 2021. Archived from the original on 29 January 2023. Retrieved 29 January 2023 – via www.reuters.com.
 "Reliance Industries Falls After Manipulation Charge, Trading Ban". Bloomberg. 27 March 2017. Archived from the original on 30 March 2017. Retrieved 29 January 2023 – via www.bloomberg.com.
 "Reliance-Rosneft Russia-India Energy Alliance". Global Finance. 26 December 2024. Archived from the original on 31 January 2025. Retrieved 29 January 2025.
 "Reliance". Leave Russia. Archived from the original on 6 February 2025. Retrieved 29 January 2025.
 "Exclusive: Rosneft, Reliance agree biggest ever India-Russia oil supply deal, sources say" Reuters (December 12, 2024)
 "Mukesh Ambani admits to differences with Anil". Rediff.com. 18 November 2004. Archived from the original on 5 August 2013. Retrieved 28 August 2013.
 "Ambani vs Ambani". India Today. 6 December 2004. Archived from the original on 19 October 2013. Retrieved 28 August 2013.
 "Reliance Industries Rights Issue Gains 15% A Day After Stellar Debut". NDTV.com. 21 May 2020. Archived from the original on 4 June 2023. Retrieved 1 March 2024.
 "Cover Story: Ambani Settlement". India Today. 4 July 2005. Archived from the original on 18 October 2013. Retrieved 28 August 2013.
 "Reliance Industries: Milestones of an oil giant". NDTV.com. Archived from the original on 2 October 2013. Retrieved 28 August 2013.
 "Corporate Announcement – Reliance Industries hands over control of Four Demerged Companies to ADAG". Bseindia.com/. 8 February 2006. Archived from the original on 19 October 2013. Retrieved 28 August 2013.
 "Reliance demerger: What should you do?". Rediff.com. 17 January 2006. Archived from the original on 19 October 2013. Retrieved 27 August 2013.
 "RIL pens demerger buyout cost". Business Standard. 17 January 2006. Archived from the original on 21 October 2013. Retrieved 28 August 2013.
 "Reliance Industries AGM full text". 21 July 2017. Archived from the original on 6 August 2017. Retrieved 21 July 2017.
 "RIL bags Refiner of the Year Award". The Economic Times. 22 March 2013. Archived from the original on 1 March 2014. Retrieved 20 August 2013.
 "India's Most Trusted Brands 2014". Archived from the original on 2 May 2015.
 "Tata, Reliance, Mahindra & Mahindra, 3 Mumbai brands among Indias 10 Most Trusted, but Delhi flexes muscles too". The Financial Express. 4 February 2014. Retrieved 26 August 2018.
 "Reliance Industries Ltd gets certified as a 'Responsible Care' under American Chemistry Council". The Economic Times. 4 March 2012. Archived from the original on 1 March 2014. Retrieved 22 August 2013.
 "Top 100 Chemical Companies 2012". ICIS.com. 10 September 2012. Archived from the original on 15 June 2014. Retrieved 22 August 2013.
 "Award for Sustainability(GPAS)". Goldenpeacockawards.com. Archived from the original on 28 February 2014. Retrieved 25 August 2013.
 "RIL named among 25 sustainable value creators globally: BCG". The Economic Times. 14 October 2009. Archived from the original on 1 March 2014. Retrieved 25 August 2013.
 "RIL among world's 100 best-managed cos". Rediff.com. 29 August 2000. Archived from the original on 18 October 2012. Retrieved 25 August 2013.
Further reading
Suryawanshi, K. Essay: The Metamorphosis of Reliance Industries. kalpesh suryawanshi.
Thakurta, P.G. and Ghosh, S. and Chaudhuri, J. (2014). GAS WARS: Crony Capitalism and the Ambanis. Paranjoy Guha Thakurta. ISBN 978-8-1928-5513-4.
McDonald, H. (1998). The Polyester Prince. Allen & Unwin. ISBN 978-1-8644-8468-7.
Rowley, C. and Rama, M. (2017). The Changing Face of Corruption in the Asia Pacific: Current Perspectives and Future Challenges. Elsevier Science. ISBN 978-0-0810-1230-7. LCCN 2016961152.
Srinivas, A. (2005). Storms in the Sea Wind: Ambani vs Ambani. Roli Books. ISBN 978-9-3519-4079-1.
Khatri, N. and Ojha, A. (2017). Crony Capitalism in India: Establishing Robust Counteractive Institutional Frameworks. Palgrave Macmillan. ISBN 978-1-1375-8287-4.
External links
Official website Edit this at Wikidata
vte
Reliance Industries
Links to related articles
Authority control databases Edit this at Wikidata
Categories: Reliance IndustriesConglomerate companies of IndiaOil and gas companies of IndiaPetrochemical companies of IndiaChemical companies of IndiaMultinational companies headquartered in IndiaMultinational oil companiesNatural gas companies of IndiaEnergy companies established in 1966Non-renewable resource companies established in 19581958 establishments in IndiaBSE SENSEXNIFTY 50Indian companies established in 1958Telecommunications companies of IndiaCompanies listed on the National Stock Exchange of IndiaCompanies listed on the Bombay Stock ExchangeWomen's Premier League (cricket) franchise ownersFamily-owned companies of India
"""

In [ ]:
question = "who is the founder of Reliance industries?"
reader(question=question, context=reliance)

{'score': 0.9981801509857178,
 'start': 21224,
 'end': 21240,
 'answer': 'Dhirubhai Ambani'}

In [ ]:
question = "where is the headoffice located?"
reader(question=question, context=reliance)

{'score': 0.9747923612594604, 'start': 86, 'end': 92, 'answer': 'Mumbai'}

In [ ]:
question = "how many children does dhirubai ambani have?"
reader(question=question, context=reliance)

{'score': 0.9605296850204468, 'start': 48510, 'end': 48513, 'answer': '521'}

In [ ]:
question = "give me the revenue details of microsoft organisation?"
reader(question=question, context=reliance)

{'score': 0.3186996281147003,
 'start': 55019,
 'end': 55046,
 'answer': 'Authority control databases'}

# translation task

In [ ]:
translate = pipeline("translation_en_to_fr")

No model was supplied, defaulted to google-t5/t5-base and revision a9723ea (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [ ]:
translate(email, max_length=1000)

[{'translation_text': "Félicitations! Vous avez obtenu votre place dans le programme de stages en science des données de Learnbay jan 2026!  Cher candidat, Félicitations! Nous sommes ravis de vous annoncer que votre profil a été sélectionné pour le prestigieux programme de stages en science des données de Learnbay jan 2026. Bienvenue au voyage de l'apprentissage, de la croissance et des possibilités intéressantes! Célébrez vos réalisations avec quelques chiffre"}]

# CONTEXT EMBEDDING  AND SEMANTIC SEARCH USING TRANSFORMER

In [ ]:
documents = [
  "Quantum mechanics describes the behavior of very small particles.",
  "Photosynthesis is the process by which green plants make food using sunlight.",
  "Shakespeare's plays are a testament to English literature.",
  "Artificial Intelligence aims to create machines that can think and learn.",
  "The pyramids of Egypt are historical monuments that have stood for thousands of years.",
  "Biology is the study of living organisms and their interactions with the environment.",
  "Music therapy can aid in the mental well-being of individuals.",
  "The Milky Way is just one of billions of galaxies in the universe.",
  "Economic theories help understand the distribution of resources in society.",
  "Yoga is an ancient practice that involves physical postures and meditation."
]

In [ ]:
!pip install -U sentence-transformers
# convert text- numbners vectors
# this is reqd for semantic search

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Collecting sentence-transformers
  Downloading sentence_transformers-5.6.1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.46.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2.32.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Downloading sentence_transformers-5.6.1-py3-none-any.whl (596 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.7/596.7 kB 39.6 MB/s eta 0:00:00
Installing collected packages: sentence-transformers
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 5.6.0
    Uninstalling sentence-transformers-5.6.0:
      Successfully uninstalled sentence-transformers-5.6.0
Successfully installed sentence-transformers-5.6.1

In [ ]:
from sentence_transformers import SentenceTransformer
from sentence_transformers import util
import torch

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
len(documents)

10

In [ ]:
documents

['Quantum mechanics describes the behavior of very small particles.',
 'Photosynthesis is the process by which green plants make food using sunlight.',
 "Shakespeare's plays are a testament to English literature.",
 'Artificial Intelligence aims to create machines that can think and learn.',
 'The pyramids of Egypt are historical monuments that have stood for thousands of years.',
 'Biology is the study of living organisms and their interactions with the environment.',
 'Music therapy can aid in the mental well-being of individuals.',
 'The Milky Way is just one of billions of galaxies in the universe.',
 'Economic theories help understand the distribution of resources in society.',
 'Yoga is an ancient practice that involves physical postures and meditation.']

In [ ]:
document_embeddings = model.encode(documents)

In [ ]:
document_embeddings.shape

(10, 384)

In [ ]:
document_embeddings

array([[ 3.6731645e-02, -2.1894886e-03, -1.3201900e-02, ...,
         6.2670894e-02, -6.6645895e-03,  2.3618026e-02],
       [-5.4819051e-02,  6.0315341e-02, -6.2531248e-02, ...,
         5.0176978e-02,  1.1442051e-01,  3.3441640e-02],
       [ 6.9595098e-02, -3.6602609e-02,  8.5741684e-02, ...,
         4.5761187e-02,  8.4835753e-02, -9.6860155e-02],
       ...,
       [ 5.7084415e-02, -6.9262117e-02,  4.4042006e-02, ...,
        -2.8854121e-02,  7.7376038e-02,  2.2505814e-02],
       [-4.0721009e-03, -8.4013620e-05, -4.0100038e-02, ...,
         1.9224878e-02,  4.2582367e-02, -5.7262544e-02],
       [-2.0348318e-02,  2.8208824e-02, -4.4747483e-02, ...,
         2.8646596e-02, -2.4007881e-02,  1.2646260e-02]], dtype=float32)

In [ ]:
pd.DataFrame(document_embeddings)

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,0.036732,-0.002189,-0.013202,0.106224,-0.013940,0.028344,-0.021976,0.054014,0.032719,0.048023,...,-0.067573,0.080089,-0.054096,-0.055388,-0.053427,-0.040769,0.034606,0.062671,-0.006665,0.023618
1,-0.054819,0.060315,-0.062531,0.033086,0.032702,-0.001572,0.017965,-0.040875,0.053273,0.059641,...,-0.096227,-0.028771,0.073358,-0.022291,-0.002371,0.047700,-0.019340,0.050177,0.114421,0.033442
2,0.069595,-0.036603,0.085742,-0.098867,-0.020527,0.123488,0.060210,-0.034376,0.011616,0.103019,...,-0.016029,-0.037842,0.005583,0.064808,-0.053949,0.008371,0.020939,0.045761,0.084836,-0.096860
3,0.010464,-0.069491,-0.000525,-0.024625,-0.011018,-0.014524,0.044609,0.021510,0.026168,0.020366,...,0.112806,0.015451,0.004376,-0.006303,0.013770,0.117532,0.060046,0.112453,0.029051,-0.037299
4,-0.020950,0.122523,-0.018798,-0.036957,-0.111285,0.014764,-0.096593,0.006840,-0.013167,-0.008917,...,0.010175,-0.081475,-0.037144,0.049025,0.064151,-0.056855,0.130973,0.015928,0.010081,-0.029052
5,0.024194,0.090609,-0.018511,0.041542,-0.019385,-0.010871,0.000349,0.005363,0.006911,0.049231,...,-0.110550,0.042432,-0.039403,-0.012983,-0.057931,0.025841,0.041288,0.072100,0.098532,-0.040797
6,0.067456,0.023052,0.056959,0.018360,-0.097674,0.129750,0.053714,0.008858,-0.018647,-0.053484,...,0.015569,0.087548,0.009737,0.127713,-0.103101,-0.060629,-0.032805,0.058485,0.053618,-0.022080
7,0.057084,-0.069262,0.044042,0.027450,-0.065534,-0.056203,-0.074272,0.039618,0.043982,-0.020910,...,-0.046378,-0.074396,-0.079889,0.020390,-0.036111,-0.010602,0.022846,-0.028854,0.077376,0.022506
8,-0.004072,-0.000084,-0.040100,-0.004620,0.087924,0.018665,0.078525,0.021548,0.031439,0.020797,...,0.019968,-0.098250,0.039598,0.037726,-0.065787,-0.016032,0.048791,0.019225,0.042582,-0.057263
9,-0.020348,0.028209,-0.044747,-0.014522,-0.030320,0.011415,0.013329,-0.091128,0.038778,0.017372,...,-0.109113,0.038137,-0.098966,0.015374,-0.055256,-0.024081,0.081734,0.028647,-0.024008,0.012646

In [ ]:
new_text = "What is Artificial Intelligence?"
new_text

'What is Artificial Intelligence?'

In [ ]:
new_text_embedding = model.encode(new_text)
pd.DataFrame(new_text_embedding)

            0
0   -0.015781
1    0.014909
2    0.009096
3    0.031317
4   -0.021708
..        ...
379  0.078875
380  0.033106
381  0.077403
382  0.107610
383 -0.053142

[384 rows x 1 columns]

COSING SIMILIARITY CHECK

In [ ]:
# CHECK THE COSINI SIMILIARITY SCORE FOR BOTH QUERY ADN THE DOCUMENT

cos_scores = util.pytorch_cos_sim(new_text_embedding, document_embeddings)[0]

In [ ]:
cos_scores

tensor([0.1441, 0.0550, 0.0615, 0.7327, 0.0504, 0.2302, 0.0598, 0.0616, 0.0913,
        0.1090])

#TOP K

In [ ]:
top_results = torch.topk(cos_scores, k=1)
top_results

torch.return_types.topk(
values=tensor([0.7327]),
indices=tensor([3]))

In [ ]:
top_results = torch.topk(cos_scores, k=2)
top_results

torch.return_types.topk(
values=tensor([0.7327, 0.2302]),
indices=tensor([3, 5]))

In [ ]:
idx = top_results.indices[0]
idx

tensor(3)

In [ ]:
documents[idx]

'Artificial Intelligence aims to create machines that can think and learn.'

In [ ]:
# Create a function to return the top similar documents based on any query

def semantic_search_engine(query, embedder_model):
  query_embedding = embedder_model.encode(query)
  cos_scores = util.pytorch_cos_sim(query_embedding, document_embeddings)[0]
  top_results = torch.topk(cos_scores, k=1)
  idx = top_results.indices[0]
  return documents[idx]

In [ ]:
q1 = "Tell me what is yoga"

In [ ]:
semantic_search_engine(q1,model)

'Yoga is an ancient practice that involves physical postures and meditation.'

In [ ]:
q2 = "Tell me about galaxy"

In [ ]:
semantic_search_engine(q2,model)

'The Milky Way is just one of billions of galaxies in the universe.'

In [ ]:
# Create a function to return the top similar documents based on any query

def semantic_search_engine(query, embedder_model):
  query_embedding = embedder_model.encode(query)
  cos_scores = util.pytorch_cos_sim(query_embedding, document_embeddings)
  top_results = torch.topk(cos_scores, k=1)
  idx = top_results.indices[0]
  return documents[idx]

In [ ]:
q2 = "Tell me about galaxy"

In [ ]:
semantic_search_engine(q2,model)

'The Milky Way is just one of billions of galaxies in the universe.'